### PR TITLE
Disable button if no scope is selected

### LINKED ISSUE #1888: Create policy button should be disabled when no scope is selected
Currently the button to create a policy is enabled as soon as the user has given the policy a name. However, if the user clicks the button before selecting a scope, the code will run into an exception. No error message is shown to the user, so from the users perspective, the button will have no function whatsoever. We should make sure the button only gets enabled, when a policy can actually be created.

### PR DESCRIPTION
**Pull request by cornelinux**
Closes #1888

### CODE REVIEW

**Review by NNLemling — COMMENTED** [review]
I've tested the whole thing on myself and it works fine. However, there is a second button below. The change should also be made for this in line 398.

**Comment by cornelinux** [comment]
@NNLemling done in 5e0e1567

**Comment by NNLemling** [comment]
sorry, i accidentally closed the pull request.

Everything works fine on my system now. So there shouldn't be anything against merging it.

**Comment by cornelinux** [comment]
@NNLemling you need to approve it and merge it

**Review by NNLemling — APPROVED** [review]

**Pull request merged**
