### PR TITLE
Highlight search terms in policy action search

### LINKED ISSUE #2577: highlight search term in policy action search
While working making the changes for #2574, I found highlighting the search terms in the policy action search would be a big pro. This can be done using angular-internals.

> During the implementation of this feature, we could also highlight the search term using the angular module ui-utils as described here
> https://angular.de/artikel/mark-highlight-search-results/

_Originally posted by @laclaro in https://github.com/privacyidea/privacyidea/issues/2178#issuecomment-759389202_

### PR DESCRIPTION
**Pull request by laclaro**
closes #2577

### CODE REVIEW

**Comment by plettich** [comment]
It is enough using only the highlight module from ui-utils. I've pushed an update to the branch.
@laclaro please check if this still works for You.

**Review by plettich — COMMENTED** [review]
Please check if my changes work for You

**Comment by laclaro** [comment]
> Please check if my changes work for You

It does, thanks for the code-diet. Please merge it.

**Review by plettich — APPROVED** [review]
looks good :-)

**Pull request merged**
