### PR TITLE
Addition of add/delete of LDAP users

### PR DESCRIPTION
**Pull request by wheldom01**
These are the additional patches for adding the add/delete LDAP users code we discussed as part of the previous set of patches.

Due to the complexity of adding users to LDAP I've added a optional callback which allows you to update the LDAP object data just prior to applying the changes to the LDAP server.

I also included a example usage, so people can see its potential.

Best Regards

Martin
<a href='#crh-start'></a><a href='#crh-data-%7B%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
<a href='https://www.codereviewhub.com/privacyidea/privacyidea/pull/369?approve=1'></a>&nbsp;<a href='https://github.com/privacyidea/privacyidea/pull/369'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by cornelinux** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/privacyidea/privacyidea/pull/369'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by cornelinux** [comment]
Hi Martin,
thanks a lot for the pull request.

I have two major comments:

# Callback
At the moment I do not get the idea of the callback. In your code you are not using the callback, so I would like to add the callback in another commit or solve the thing in another way.

I assume the idea of the callback is, that a newly created user should be member in certain groups e.g.

Maybe this can be solved in another way: Like additional configuration of the resolver. Most privacyIDEA users probably would not create callback functions from my experience. And: If your Active Directory or LDAP is to complex, you probably would not manage the users within privacyIDEA ;-)

So please remove the callback in this PR.

# Rebase
Can you please rebase your changes to one commit, so that it looks cleaner.

I will close the PR for now.
Please issue an new, rebased PR.

Thanks a lot
Cornelius

**Comment by wheldom01** [comment]
Hi Cornelius,

No problem, I'll address both of this issues.

Thanks
Martin

**Comment by cornelinux** [comment]
thx!

**Pull request closed without merging**
