### PR TITLE
Do not delete existing apache config files

### PR DESCRIPTION
**Pull request by Techwolf12**
Apache config files should not be deleted upon installation of this package. Please tell the user to do something like this manually to prevent deletion of existing configurations.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/privacyidea/privacyidea/pull/1198%23issuecomment-415760495%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/privacyidea/privacyidea/pull/1198%23issuecomment-415760495%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%20%5BCodecov%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1198%3Fsrc%3Dpr%26el%3Dh1%29%20Report%5Cn%3E%20Merging%20%5B%231198%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1198%3Fsrc%3Dpr%26el%3Ddesc%29%20into%20%5Bmaster%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/commit/6cf051564ab965c2c476c58f9de14c85ae92379f%3Fsrc%3Dpr%26el%3Ddesc%29%20will%20%2A%2Anot%20change%2A%2A%20coverage.%5Cn%3E%20The%20diff%20coverage%20is%20%60n/a%60.%5Cn%5Cn%5B%21%5BImpacted%20file%20tree%20graph%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1198/graphs/tree.svg%3Fsrc%3Dpr%26token%3D7nHLZki60B%26height%3D150%26width%3D650%29%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1198%3Fsrc%3Dpr%26el%3Dtree%29%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20Coverage%20Diff%20%20%20%20%20%20%20%20%20%20%20%40%40%5Cn%23%23%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%231198%20%20%20%2B/-%20%20%20%23%23%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%20%20Coverage%20%20%2095.77%25%20%20%2095.77%25%20%20%20%20%20%20%20%20%20%20%20%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%20%20Files%20%20%20%20%20%20%20%20%20141%20%20%20%20%20%20141%20%20%20%20%20%20%20%20%20%20%20%5Cn%20%20Lines%20%20%20%20%20%20%2017119%20%20%20%2017119%20%20%20%20%20%20%20%20%20%20%20%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%20%20Hits%20%20%20%20%20%20%20%2016395%20%20%20%2016395%20%20%20%20%20%20%20%20%20%20%20%5Cn%20%20Misses%20%20%20%20%20%20%20%20724%20%20%20%20%20%20724%5Cn%60%60%60%5Cn%5Cn%5Cn%5Cn------%5Cn%5Cn%5BContinue%20to%20review%20full%20report%20at%20Codecov%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1198%3Fsrc%3Dpr%26el%3Dcontinue%29.%5Cn%3E%20%2A%2ALegend%2A%2A%20-%20%5BClick%20here%20to%20learn%20more%5D%28https%3A//docs.codecov.io/docs/codecov-delta%29%5Cn%3E%20%60%5Cu0394%20%3D%20absolute%20%3Crelative%3E%20%28impact%29%60%2C%20%60%5Cu00f8%20%3D%20not%20affected%60%2C%20%60%3F%20%3D%20missing%20data%60%5Cn%3E%20Powered%20by%20%5BCodecov%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1198%3Fsrc%3Dpr%26el%3Dfooter%29.%20Last%20update%20%5B6cf0515...cd43c2f%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1198%3Fsrc%3Dpr%26el%3Dlastupdated%29.%20Read%20the%20%5Bcomment%20docs%5D%28https%3A//docs.codecov.io/docs/pull-request-comments%29.%5Cn%22%2C%20%22created_at%22%3A%20%222018-08-24T13%3A35%3A00Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/in/254%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/apps/codecov%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/privacyidea/privacyidea/pull/1198#issuecomment-415760495'>General Comment</a></b>
- <a href='https://github.com/apps/codecov'></a> # [Codecov](https://codecov.io/gh/privacyidea/privacyidea/pull/1198?src=pr&el=h1) Report
> Merging [#1198](https://codecov.io/gh/privacyidea/privacyidea/pull/1198?src=pr&el=desc) into [master](https://codecov.io/gh/privacyidea/privacyidea/commit/6cf051564ab965c2c476c58f9de14c85ae92379f?src=pr&el=desc) will **not change** coverage.
> The diff coverage is `n/a`.
[Impacted file tree graph](https://codecov.io/gh/privacyidea/privacyidea/pull/1198?src=pr&el=tree)
```diff
@@           Coverage Diff           @@
##           master    #1198   +/-   ##
=======================================
Coverage   95.77%   95.77%
=======================================
Files         141      141
Lines       17119    17119
=======================================
Hits        16395    16395
Misses        724      724
```
------
[Continue to review full report at Codecov](https://codecov.io/gh/privacyidea/privacyidea/pull/1198?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/privacyidea/privacyidea/pull/1198?src=pr&el=footer). Last update [6cf0515...cd43c2f](https://codecov.io/gh/privacyidea/privacyidea/pull/1198?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

<a href='https://www.codereviewhub.com/privacyidea/privacyidea/pull/1198?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/privacyidea/privacyidea/pull/1198?approve=1'></a>&nbsp;<a href='https://github.com/privacyidea/privacyidea/pull/1198'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by cornelinux** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/privacyidea/privacyidea/pull/1198'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by cornelinux** [comment]
Thanks a lot for your concern!
We had this discussion before - we had such an issue before.
This is a meta package that is ment to create a privacyIDEA server from a standard installation. This is why we kept it this way back then and we also keep it this way, now.

There is a prominent note in the documentation, that existing apache configurations get deactivated.
So we keep it this way.

If you do *not* want to create a privacyIDEA server using the meta package, then you still can only install *python-privacyidea* and optional *privacyidea-mysql* and configure your apache setup manually.

**Comment by Techwolf12** [comment]
Hmm, how about copying all config to /tmp/apache first before deleting. Worst case senario you can still access the config.
Not everyone places configs in sites-available (they should, but you know how it goes) and not everyone knows which configs they had enabled.

**Comment by cornelinux** [comment]
It is not our intention to destroy any data of the user - even if the user is so off standards and would create real files in ``sites-enabled``. :-/

Well, till now I did not hear of such problem, that acutally config files were destroyed. Did you hear of that? 
I do not like to store too many files. In 99,9% there will be links in ``sites-available``, so we do not need "backups".

If we backup files, I would only backup reals files. - maybe using find.
Would you rework your PR?

**Comment by Techwolf12** [comment]
>Well, till now I did not hear of such problem, that acutally config files were destroyed. Did you hear of that?

Yep, all our existing apache config was destroyed upon installing the package. I could recover it from a virtual machine backup though.

> If we backup files, I would only backup reals files. - maybe using find.

Even if you only backup real files you still have the issue of config's getting disabled (and if you don't know which should've been enabled).

So a possible solution is a list of files in the folder (all the active configs, including symlinks) and backups of real files in the folder?

**Pull request closed without merging**
