### PR TITLE
Fix serial length

### PR DESCRIPTION
**Pull request by fredreichbier**
This is #728 by @salvorapi with an additional migration script.

@cornelinux This is my first migration script -- What do you think about it? :) Unfortunately, it does not seem to work on SQLite:
```
Running online
Could not enlarge column 'pidea_audit.serial'
(sqlite3.OperationalError) near "ALTER": syntax error [SQL: u'ALTER TABLE pidea_audit ALTER COLUMN serial TYPE VARCHAR(40)']
```
But I guess this is [known behavior](http://alembic.zzzcomputing.com/en/latest/batch.html)?
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/privacyidea/privacyidea/pull/929%23issuecomment-365657090%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/929%23issuecomment-366229640%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/929%23issuecomment-367036409%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/929%23issuecomment-367037858%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/929%23issuecomment-367038718%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/929%23issuecomment-367039117%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/929%23issuecomment-367334526%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/929%23issuecomment-367589877%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/929%23issuecomment-367774617%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/privacyidea/privacyidea/pull/929%23issuecomment-365657090%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%20%5BCodecov%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/929%3Fsrc%3Dpr%26el%3Dh1%29%20Report%5Cn%3E%20Merging%20%5B%23929%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/929%3Fsrc%3Dpr%26el%3Ddesc%29%20into%20%5Bmaster%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/commit/568abb116dca36e46ac1f1bd9c32be6eeba8f580%3Fsrc%3Dpr%26el%3Ddesc%29%20will%20%2A%2Anot%20change%2A%2A%20coverage.%5Cn%3E%20The%20diff%20coverage%20is%20%60n/a%60.%5Cn%5Cn%5B%21%5BImpacted%20file%20tree%20graph%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/929/graphs/tree.svg%3Fwidth%3D650%26token%3D7nHLZki60B%26height%3D150%26src%3Dpr%29%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/929%3Fsrc%3Dpr%26el%3Dtree%29%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20Coverage%20Diff%20%20%20%20%20%20%20%20%20%20%20%40%40%5Cn%23%23%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%20%23929%20%20%20%2B/-%20%20%20%23%23%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%20%20Coverage%20%20%2095.41%25%20%20%2095.41%25%20%20%20%20%20%20%20%20%20%20%20%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%20%20Files%20%20%20%20%20%20%20%20%20129%20%20%20%20%20%20129%20%20%20%20%20%20%20%20%20%20%20%5Cn%20%20Lines%20%20%20%20%20%20%2016018%20%20%20%2016018%20%20%20%20%20%20%20%20%20%20%20%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%20%20Hits%20%20%20%20%20%20%20%2015284%20%20%20%2015284%20%20%20%20%20%20%20%20%20%20%20%5Cn%20%20Misses%20%20%20%20%20%20%20%20734%20%20%20%20%20%20734%5Cn%60%60%60%5Cn%5Cn%5Cn%7C%20%5BImpacted%20Files%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/929%3Fsrc%3Dpr%26el%3Dtree%29%20%7C%20Coverage%20%5Cu0394%20%7C%20%7C%5Cn%7C---%7C---%7C---%7C%5Cn%7C%20%5Bprivacyidea/models.py%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/929/diff%3Fsrc%3Dpr%26el%3Dtree%23diff-cHJpdmFjeWlkZWEvbW9kZWxzLnB5%29%20%7C%20%6098.74%25%20%3C%5Cu00f8%3E%20%28%5Cu00f8%29%60%20%7C%20%3Aarrow_up%3A%20%7C%5Cn%5Cn------%5Cn%5Cn%5BContinue%20to%20review%20full%20report%20at%20Codecov%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/929%3Fsrc%3Dpr%26el%3Dcontinue%29.%5Cn%3E%20%2A%2ALegend%2A%2A%20-%20%5BClick%20here%20to%20learn%20more%5D%28https%3A//docs.codecov.io/docs/codecov-delta%29%5Cn%3E%20%60%5Cu0394%20%3D%20absolute%20%3Crelative%3E%20%28impact%29%60%2C%20%60%5Cu00f8%20%3D%20not%20affected%60%2C%20%60%3F%20%3D%20missing%20data%60%5Cn%3E%20Powered%20by%20%5BCodecov%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/929%3Fsrc%3Dpr%26el%3Dfooter%29.%20Last%20update%20%5B568abb1...6ab5a2c%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/929%3Fsrc%3Dpr%26el%3Dlastupdated%29.%20Read%20the%20%5Bcomment%20docs%5D%28https%3A//docs.codecov.io/docs/pull-request-comments%29.%5Cn%22%2C%20%22created_at%22%3A%20%222018-02-14T16%3A12%3A07Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars0.githubusercontent.com/u/8655789%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/codecov-io%22%7D%7D%2C%20%7B%22body%22%3A%20%22This%20looks%20totally%20legit.%5Cr%5CnI%20am%20wondering%2C%20if%20we%20should%20add%20release%20notes%20either%20as%20an%20extra%20file%20or%20in%20the%20changelog.%5Cr%5Cn%5Cr%5CnThere%20is%20also%20a%20field%20enhancement%20in%20%23913.%5Cr%5Cn%5Cr%5CnA%20release%20note%20would%20read%20like%3A%5Cr%5Cn%5Cr%5Cn%3E%20Release%202.22%5Cr%5Cn%3E%20%2A%20The%20column%20%5C%22seriral%5C%22%20in%20table...%20was%20enhanced%20to...%20The%20migration%20script%20does%20this%20automatically...%20Note%3A%20Verify%20that%20your%20database%20server%20will%20be%20capable%20of%20handling%20the%20overall%20table%20length.%5Cr%5Cn%3E%20%2A%20The%20column%20%5C%22client%5C%22%20in%20table%20policy....%5Cr%5Cn%5Cr%5CnAs%20we%20can%20not%20know%20all%20database%20setups%2C%20it%20might%20be%20wise%20to%20add%20this%20information%20either%20in%20an%20extra%20RELEASE_NOTES.txt%20or%20add%20it%20prominently%20to%20the%20CHANGELOG.%20%5Cr%5CnHow%20would%20you%20add%20this%20to%20the%20changelog%3F%22%2C%20%22created_at%22%3A%20%222018-02-16T13%3A03%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/1908620%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%2C%20%7B%22body%22%3A%20%22Hm%2C%20I%27m%20not%20sure.%20I%20would%20think%20that%20the%20CHANGELOG%20is%20not%20really%20the%20right%20place%2C%20as%20it%27s%20more%20a%20summary%20of%20changes%20than%20some%20%5C%22Read-before-Update%5C%22%20...%20maybe%20we%20can%20add%20a%20RELEASE_NOTES.txt%20that%20gets%20printed%20during%20the%20update%3F%20%28not%20sure%20if%20anybody%20reads%20that%2C%20though%29%5Cr%5Cn%5Cr%5CnDo%20we%20support%20SQLite%20installations%3F%20Because%20there%2C%20the%20migration%20won%27t%20work.%22%2C%20%22created_at%22%3A%20%222018-02-20T16%3A34%3A51Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/28243%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/fredreichbier%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5C%22The%20migration%20won%27t%20work%20on%20sqlite%5C%22%3F%5Cr%5Cn%5Cr%5CnYes%2C%20at%20least%20we%20support%20it%20for%20testing%20purposes.%20But%20I%20guess%20the%20except%20block%20will%20catch%20any%20problem%20with%20SQLite%3F%5Cr%5Cn%5Cr%5CnPrinting%20anything%20before%20update%20is%20impossible.%20There%20are%20two%20many%20ways%20to%20update.%20And%20no%20one%20will%20read%20it.%20Then%20I%20would%20prefer%20a%20RELEASE_NOTES.txt%2C%20which%20admins%20should%20consider%20to%20read.%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222018-02-20T16%3A39%3A11Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/1908620%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%2C%20%7B%22body%22%3A%20%22Exactly%2C%20the%20except%20block%20catches%20it%3A%5Cr%5Cn%60%60%60Could%20not%20enlarge%20column%20%27pidea_audit.serial%27%5Cr%5Cn%28sqlite3.OperationalError%29%20near%20%5C%22ALTER%5C%22%3A%20syntax%20error%20%5BSQL%3A%20u%27ALTER%20TABLE%20pidea_audit%20ALTER%20COLUMN%20serial%20TYPE%20VARCHAR%2840%29%27%5D%5Cr%5Cn%60%60%60%5Cr%5CnSo%20I%20guess%20that%27s%20okay%20%3A-%29%5Cr%5Cn%5Cr%5Cn%40%20Release%20Notes%3A%20Sounds%20good%20to%20me%21%22%2C%20%22created_at%22%3A%20%222018-02-20T16%3A41%3A50Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/28243%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/fredreichbier%22%7D%7D%2C%20%7B%22body%22%3A%20%22Well%2C%20I%20think%20there%20is%20a%20common%20understand%2C%20that%20release%20notes%20contain%20mostly%20the%20stuff%2C%20that%20we%20put%20into%20the%20changelog.%5Cr%5Cn%5Cr%5Cnhttps%3A//en.wikipedia.org/wiki/Release_notes%5Cr%5Cnhttps%3A//stackoverflow.com/questions/638423/how-should-release-notes-be-written%5Cr%5Cn%5Cr%5CnActually%20what%20we%20want%20is%20a%20document%20READ_BEFORE_UPDATE...%5Cr%5Cn%5Cr%5CnIn%20regards%20to%20sqlite%20-%20I%20think%20the%20problem%20is%2C%20that%20sqlite%20does%20not%20know%20a%20%2A%2Alength%2A%2A%20of%20a%20varchar.%5Cr%5CnBut%20honestly%2C%20this%20sounds%20like%20a%20flaw%20in%20sqlalchemy%20migrate%20script...%22%2C%20%22created_at%22%3A%20%222018-02-20T16%3A43%3A05Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/1908620%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%2C%20%7B%22body%22%3A%20%22%2B1%20to%20READ_BEFORE_UPDATE%20if%20we%20can%20write%20such%20a%20document%20%3A%29%5Cr%5Cn%5Cr%5CnRegarding%20the%20sqlite%20problems%3A%20I%20think%20the%20problem%20is%20that%20SQlite%20does%20not%20really%20support%20%5C%22ALTER%20TABLE%5C%22.%20So%20we%20generally%20have%20a%20problem%20with%20SQlite%20and%20migrations%20that%20alter%20columns.%20However%2C%20alembic%200.7.0%20adds%20%5BBatch%20Migrations%5D%28http%3A//alembic.zzzcomputing.com/en/latest/batch.html%29%20as%20a%20workaround.%20However%2C%20they%27re%20considered%20beta%20and%20we%27re%20using%20an%20older%20alembic%200.6.7%20anyway.%22%2C%20%22created_at%22%3A%20%222018-02-21T14%3A00%3A27Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/28243%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/fredreichbier%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20think%20we%20can%20let%20the%20%60%60except%60%60%20catch%20the%20SQLite%20exception.%5Cr%5Cn%5Cr%5CnI%20will%20add%20a%20READ_BEFORE_UPDATE%20document.%22%2C%20%22created_at%22%3A%20%222018-02-22T07%3A22%3A23Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/1908620%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%2C%20%7B%22body%22%3A%20%22looks%20good%20to%20me%21%22%2C%20%22created_at%22%3A%20%222018-02-22T18%3A26%3A37Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/1908620%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/privacyidea/privacyidea/pull/929#issuecomment-365657090'>General Comment</a></b>
- <a href='https://github.com/codecov-io'></a> # [Codecov](https://codecov.io/gh/privacyidea/privacyidea/pull/929?src=pr&el=h1) Report
> Merging [#929](https://codecov.io/gh/privacyidea/privacyidea/pull/929?src=pr&el=desc) into [master](https://codecov.io/gh/privacyidea/privacyidea/commit/568abb116dca36e46ac1f1bd9c32be6eeba8f580?src=pr&el=desc) will **not change** coverage.
> The diff coverage is `n/a`.
[Impacted file tree graph](https://codecov.io/gh/privacyidea/privacyidea/pull/929?src=pr&el=tree)
```diff
@@           Coverage Diff           @@
##           master     #929   +/-   ##
=======================================
Coverage   95.41%   95.41%
=======================================
Files         129      129
Lines       16018    16018
=======================================
Hits        15284    15284
Misses        734      734
```
| [Impacted Files](https://codecov.io/gh/privacyidea/privacyidea/pull/929?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [privacyidea/models.py](https://codecov.io/gh/privacyidea/privacyidea/pull/929/diff?src=pr&el=tree#diff-cHJpdmFjeWlkZWEvbW9kZWxzLnB5) | `98.74% <ø> (ø)` | :arrow_up: |
------
[Continue to review full report at Codecov](https://codecov.io/gh/privacyidea/privacyidea/pull/929?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/privacyidea/privacyidea/pull/929?src=pr&el=footer). Last update [568abb1...6ab5a2c](https://codecov.io/gh/privacyidea/privacyidea/pull/929?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).
- <a href='https://github.com/cornelinux'></a> This looks totally legit.
I am wondering, if we should add release notes either as an extra file or in the changelog.
There is also a field enhancement in #913.
A release note would read like:
> Release 2.22
> * The column "seriral" in table... was enhanced to... The migration script does this automatically... Note: Verify that your database server will be capable of handling the overall table length.
> * The column "client" in table policy....
As we can not know all database setups, it might be wise to add this information either in an extra RELEASE_NOTES.txt or add it prominently to the CHANGELOG.
How would you add this to the changelog?
- <a href='https://github.com/fredreichbier'></a> Hm, I'm not sure. I would think that the CHANGELOG is not really the right place, as it's more a summary of changes than some "Read-before-Update" ... maybe we can add a RELEASE_NOTES.txt that gets printed during the update? (not sure if anybody reads that, though)
Do we support SQLite installations? Because there, the migration won't work.
- <a href='https://github.com/cornelinux'></a> "The migration won't work on sqlite"?
Yes, at least we support it for testing purposes. But I guess the except block will catch any problem with SQLite?
Printing anything before update is impossible. There are two many ways to update. And no one will read it. Then I would prefer a RELEASE_NOTES.txt, which admins should consider to read.
- <a href='https://github.com/fredreichbier'></a> Exactly, the except block catches it:
```Could not enlarge column 'pidea_audit.serial'
(sqlite3.OperationalError) near "ALTER": syntax error [SQL: u'ALTER TABLE pidea_audit ALTER COLUMN serial TYPE VARCHAR(40)']
```
So I guess that's okay :-)
@ Release Notes: Sounds good to me!
- <a href='https://github.com/cornelinux'></a> Well, I think there is a common understand, that release notes contain mostly the stuff, that we put into the changelog.
https://en.wikipedia.org/wiki/Release_notes
https://stackoverflow.com/questions/638423/how-should-release-notes-be-written
Actually what we want is a document READ_BEFORE_UPDATE...
In regards to sqlite - I think the problem is, that sqlite does not know a **length** of a varchar.
But honestly, this sounds like a flaw in sqlalchemy migrate script...
- <a href='https://github.com/fredreichbier'></a> +1 to READ_BEFORE_UPDATE if we can write such a document :)
Regarding the sqlite problems: I think the problem is that SQlite does not really support "ALTER TABLE". So we generally have a problem with SQlite and migrations that alter columns. However, alembic 0.7.0 adds [Batch Migrations](http://alembic.zzzcomputing.com/en/latest/batch.html) as a workaround. However, they're considered beta and we're using an older alembic 0.6.7 anyway.
- <a href='https://github.com/cornelinux'></a> I think we can let the ``except`` catch the SQLite exception.
I will add a READ_BEFORE_UPDATE document.
- <a href='https://github.com/cornelinux'></a> looks good to me!

<a href='https://www.codereviewhub.com/privacyidea/privacyidea/pull/929?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/privacyidea/privacyidea/pull/929?approve=1'></a>&nbsp;<a href='https://github.com/privacyidea/privacyidea/pull/929'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by cornelinux** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/privacyidea/privacyidea/pull/929'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by cornelinux** [comment]
This looks totally legit.
I am wondering, if we should add release notes either as an extra file or in the changelog.

There is also a field enhancement in #913.

A release note would read like:

> Release 2.22
> * The column "seriral" in table... was enhanced to... The migration script does this automatically... Note: Verify that your database server will be capable of handling the overall table length.
> * The column "client" in table policy....

As we can not know all database setups, it might be wise to add this information either in an extra RELEASE_NOTES.txt or add it prominently to the CHANGELOG. 
How would you add this to the changelog?

**Comment by fredreichbier** [comment]
Hm, I'm not sure. I would think that the CHANGELOG is not really the right place, as it's more a summary of changes than some "Read-before-Update" ... maybe we can add a RELEASE_NOTES.txt that gets printed during the update? (not sure if anybody reads that, though)

Do we support SQLite installations? Because there, the migration won't work.

**Comment by cornelinux** [comment]
"The migration won't work on sqlite"?

Yes, at least we support it for testing purposes. But I guess the except block will catch any problem with SQLite?

Printing anything before update is impossible. There are two many ways to update. And no one will read it. Then I would prefer a RELEASE_NOTES.txt, which admins should consider to read.

**Comment by fredreichbier** [comment]
Exactly, the except block catches it:
```Could not enlarge column 'pidea_audit.serial'
(sqlite3.OperationalError) near "ALTER": syntax error [SQL: u'ALTER TABLE pidea_audit ALTER COLUMN serial TYPE VARCHAR(40)']
```
So I guess that's okay :-)

@ Release Notes: Sounds good to me!

**Comment by cornelinux** [comment]
Well, I think there is a common understand, that release notes contain mostly the stuff, that we put into the changelog.

https://en.wikipedia.org/wiki/Release_notes
https://stackoverflow.com/questions/638423/how-should-release-notes-be-written

Actually what we want is a document READ_BEFORE_UPDATE...

In regards to sqlite - I think the problem is, that sqlite does not know a **length** of a varchar.
But honestly, this sounds like a flaw in sqlalchemy migrate script...

**Comment by fredreichbier** [comment]
+1 to READ_BEFORE_UPDATE if we can write such a document :)

Regarding the sqlite problems: I think the problem is that SQlite does not really support "ALTER TABLE". So we generally have a problem with SQlite and migrations that alter columns. However, alembic 0.7.0 adds [Batch Migrations](http://alembic.zzzcomputing.com/en/latest/batch.html) as a workaround. However, they're considered beta and we're using an older alembic 0.6.7 anyway.

**Comment by cornelinux** [comment]
looks good to me!

**Pull request merged**
