### PR TITLE
Check client definition

### LINKED ISSUE #2949: Check the client definition during creation of a policy
**Is your feature request related to a problem? Please describe.**

The function [check_ip_in_policy](https://github.com/privacyidea/privacyidea/blob/982329aa684ad096e7836e048d808aaca6ece4b9/privacyidea/lib/utils/__init__.py#L712) verifies if the given client IP is contained in the given IP settings list.
However, if the list contains an invalid IP definition, it raises a 500 Error as expected.

We should use this very same function (check_ip_in_policy) during the creation of a policy, so that we already raise an error during the saving of the policy.

**Describe the solution you'd like**

We should check this on the library level [here](https://github.com/privacyidea/privacyidea/blob/2d240464961dfdc2f1a6560ed99fa051e543c6b7/privacyidea/lib/policy.py#L1338). We can ignore the outcome and simply use the fact, that an invalid definition raises an exception:

~~~~python
    if type(client) == list:
        client = ", ".join(client)
    # It does not matter, which IP we check. An invalid "client" definition will raise an exception
    check_ip_in_policy("127.0.0.1", client.split(","))
~~~~

**Describe alternatives you've considered**

None

**Additional context**

Do not forget the start with some tests in test_api_policy.

### PR DESCRIPTION
**Pull request by NNLemling**
- [x] Add function
- [x] Add test
- [x] Adjusted existing tests

Closes #2949

### CODE REVIEW

**Comment by NNLemling** [comment]
All the python tests are failing.

It may be because no client is defined in most of the tests. In fact, it would be a lot of work to manually adjust all tests. Maybe someone could give me a tip on how to solve this more easily.

**Comment by cornelinux** [comment]
OK, I think we should default the `client` to an empty list, since `check_ip_in_policy` expects a list.

~~~~python
client = client or []
~~~~

before calling check_ip_in_policy.

**Comment by cornelinux** [comment]
I fixed it in bb6b2b12. When the testst are through, we can merge it.

**Review by cornelinux — APPROVED** [review]

**Comment by NNLemling** [comment]
Cool! I actually had and tested a similar solution. More tests have been successfully completed but still not all. But your change is a little different. Hopefully, all tests will now pass. Thank you for the effort!

**Comment by cornelinux** [comment]
@NNLemling we can take a look together at my last changes.

**Pull request merged**
