### PR TITLE
Add filter for token attribute in token janitor

### PR DESCRIPTION
**Pull request by cornelinux**
We can now use the tokenattribute filter in the
token-janitor. It matches the columns of the Token
table directly.
The available columns are read from the database definition.

The filter creation method for tokeninfo is used.

This allows us to filter for the column "rollout_state".

Working on #2784

### CODE REVIEW

**Review by Sebastian-Lemling — COMMENTED** [review]
It works well for me.

but in some cases, for example with "ID" or "maxfail", a string is expected but an integer is passed. This leads to an error message that should be intercepted if necessary.

Perhaps this error should also be corrected, because it is not possible to filter for attributes where an integer is passed.

**Comment by cornelinux** [comment]
The problem is, I did this like with the tokeninfo. But the tokeninfo is alway a string. So the equal comparison with strings in tokeninf, that contain a number, works out fine with the string comparison. However, the integer fields in the tokenattributes do not.
I will add an extra comparison.

**Comment by cornelinux** [comment]
@NNLemling I fixed it this way, that you can now run this:

Match exact integer:

    privacyidea-token-janitor find --tokenattribute id --tokenattribute-value 10

Match a regular expression string:

    privacyidea-token-janitor find --tokenattribute serial --tokenattribute-value 'TOTP.*'

**Comment by NNLemling** [comment]
I just tested it and it works perfectly!

**Review by Sebastian-Lemling — APPROVED** [review]

**Pull request merged**
