### PR TITLE
Fix serial length on Audit model

### PR DESCRIPTION
**Pull request by salvorapi**
Length of serial column is different between Audit and Token model.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/privacyidea/privacyidea/pull/728%23issuecomment-310321921%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/728%23issuecomment-310326245%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/728%23issuecomment-313655127%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/728%23issuecomment-313658163%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/728%23issuecomment-313678163%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/728%23issuecomment-313777031%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/728%23issuecomment-313844155%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/728%23issuecomment-313849506%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/728%23issuecomment-364442685%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/728%23issuecomment-364564678%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/728%23issuecomment-364581376%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/privacyidea/privacyidea/pull/728%23issuecomment-310321921%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%20%5BCodecov%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/728%3Fsrc%3Dpr%26el%3Dh1%29%20Report%5Cn%3E%20Merging%20%5B%23728%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/728%3Fsrc%3Dpr%26el%3Ddesc%29%20into%20%5Bmaster%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/commit/512cbdb6c4b497c4d04006528d49bf0d98d752c6%3Fsrc%3Dpr%26el%3Ddesc%29%20will%20%2A%2Adecrease%2A%2A%20coverage%20by%20%600.03%25%60.%5Cn%3E%20The%20diff%20coverage%20is%20%60n/a%60.%5Cn%5Cn%5B%21%5BImpacted%20file%20tree%20graph%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/728/graphs/tree.svg%3Ftoken%3D7nHLZki60B%26width%3D650%26src%3Dpr%26height%3D150%29%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/728%3Fsrc%3Dpr%26el%3Dtree%29%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20Coverage%20Diff%20%20%20%20%20%20%20%20%20%20%20%20%40%40%5Cn%23%23%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23728%20%20%20%20%20%20%2B/-%20%20%20%23%23%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn-%20Coverage%20%20%2095.34%25%20%20%2095.3%25%20%20%20-0.04%25%20%20%20%20%20%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%20%20Files%20%20%20%20%20%20%20%20%20121%20%20%20%20%20121%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5Cn%20%20Lines%20%20%20%20%20%20%2014818%20%20%2014818%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn-%20Hits%20%20%20%20%20%20%20%2014128%20%20%2014123%20%20%20%20%20%20%20-5%20%20%20%20%20%5Cn-%20Misses%20%20%20%20%20%20%20%20690%20%20%20%20%20695%20%20%20%20%20%20%20%2B5%5Cn%60%60%60%5Cn%5Cn%5Cn%7C%20%5BImpacted%20Files%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/728%3Fsrc%3Dpr%26el%3Dtree%29%20%7C%20Coverage%20%5Cu0394%20%7C%20%7C%5Cn%7C---%7C---%7C---%7C%5Cn%7C%20%5Bprivacyidea/models.py%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/728%3Fsrc%3Dpr%26el%3Dtree%23diff-cHJpdmFjeWlkZWEvbW9kZWxzLnB5%29%20%7C%20%6098.68%25%20%3C%5Cu00f8%3E%20%28%5Cu00f8%29%60%20%7C%20%3Aarrow_up%3A%20%7C%5Cn%7C%20%5Bprivacyidea/lib/tokens/u2f.py%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/728%3Fsrc%3Dpr%26el%3Dtree%23diff-cHJpdmFjeWlkZWEvbGliL3Rva2Vucy91MmYucHk%3D%29%20%7C%20%6091.59%25%20%3C0%25%3E%20%28-4.21%25%29%60%20%7C%20%3Aarrow_down%3A%20%7C%5Cn%5Cn------%5Cn%5Cn%5BContinue%20to%20review%20full%20report%20at%20Codecov%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/728%3Fsrc%3Dpr%26el%3Dcontinue%29.%5Cn%3E%20%2A%2ALegend%2A%2A%20-%20%5BClick%20here%20to%20learn%20more%5D%28https%3A//docs.codecov.io/docs/codecov-delta%29%5Cn%3E%20%60%5Cu0394%20%3D%20absolute%20%3Crelative%3E%20%28impact%29%60%2C%20%60%5Cu00f8%20%3D%20not%20affected%60%2C%20%60%3F%20%3D%20missing%20data%60%5Cn%3E%20Powered%20by%20%5BCodecov%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/728%3Fsrc%3Dpr%26el%3Dfooter%29.%20Last%20update%20%5B512cbdb...03da416%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/728%3Fsrc%3Dpr%26el%3Dlastupdated%29.%20Read%20the%20%5Bcomment%20docs%5D%28https%3A//docs.codecov.io/docs/pull-request-comments%29.%5Cn%22%2C%20%22created_at%22%3A%20%222017-06-22T09%3A05%3A39Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/8655789%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/codecov-io%22%7D%7D%2C%20%7B%22body%22%3A%20%22Thanks%20a%20lot%20for%20the%20heads%20up.%5Cr%5CnEach%20database%20change%20needs%20a%20migration%20script%20in%20%2Amigrations/%2A.%5Cr%5CnThe%20command%20%5Cr%5Cn%5Cr%5Cn%20%20%20pi-manage%20db%20migrate%5Cr%5Cn%5Cr%5Cnwill%20create%20a%20default%20migration%20script%20%28with%20some%20junk%29.%20%5Cr%5CnCould%20you%20also%20add%20this%20migration%20script%20and%20also%20add%20a%20try/except%20block%2C%20just%20like%20with%20the%20other%20migration%20scripts%3F%22%2C%20%22created_at%22%3A%20%222017-06-22T09%3A23%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/1908620%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%2C%20%7B%22body%22%3A%20%22Hi%2C%5Cr%5Cn%5Cr%5CnI%27ve%20cloned%20repository%20on%20my%20VM%20and%20create%20python%20env%20with%20requirements.txt%5Cr%5CnI%20try%20to%20do%20the%20command%3A%5Cr%5Cn%5Cr%5Cnpi-manage%20createdb%5Cr%5Cn%5Cr%5Cnand%20then%5Cr%5Cn%5Cr%5Cnpi-manage%20db%20upgrade%5Cr%5Cn%5Cr%5Cnbut%20I%20have%20the%20error%3A%5Cr%5Cn%5Cr%5Cnindex%20ix_token_user_id%20already%20exists%20%5BSQL%3A%20u%27CREATE%20INDEX%20ix_token_user_id%20ON%20token%20%28user_id%29%27%5D%5Cr%5Cn%5Cr%5CnHow%20I%20do%20apply%20last%20upgrade%20on%20DB%20so%20next%20I%20will%20create%20new%20migration%20%3F%5Cr%5Cn%5Cr%5CnThank%20you.%5Cr%5Cn%5Cr%5CnSalvo.%22%2C%20%22created_at%22%3A%20%222017-07-07T11%3A18%3A36Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/6554709%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/salvorapi%22%7D%7D%2C%20%7B%22body%22%3A%20%22Please%20run%5Cr%5Cn%5Cr%5Cn%20%20%20%20./pi-manage%5Cr%5Cn%5Cr%5Cn%28You%20probably%20did%20this%29%5Cr%5Cn%5Cr%5CnWhen%20you%20initially%20create%20the%20database%20you%20probably%20have%20not%20alembic%20versioning%20talbe%20in%20it.%20you%20need%20to%20create%20this%20like%5Cr%5Cn%5Cr%5Cn%20%20%20%20./pi-manage%20db%20stamp%20%204f32a4e1bf33%20%5Cr%5Cn%5Cr%5Cn%28see%20http%3A//privacyidea.readthedocs.io/en/latest/installation/upgrade.html%3Fhighlight%3Dpi-manage%2520stamp%23manual-upgrade%29%5Cr%5CnThis%20%60%60stamp%60%60%20will%20create%20the%20version%20table%20andin%20this%20case%20set%20the%20version%20to%20the%20first%20version.%5Cr%5CnNow%20you%20can%20run%5Cr%5Cn%5Cr%5Cn%20%20%20%20./pi-manage%20db%20upgrade%5Cr%5Cn%5Cr%5CnWell%2C%20you%20will%20get%20a%20lot%20of%20errors%20you%20can%20ignore%2C%20but%20now%20you%20have%20the%20talbe%20%60%60alembic_version%60%60.%22%2C%20%22created_at%22%3A%20%222017-07-07T11%3A36%3A22Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/1908620%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%2C%20%7B%22body%22%3A%20%22Hi%2C%5Cr%5Cn%5Cr%5Cnwhat%20I%27ve%20done%20is%3A%5Cr%5Cn%5Cr%5Cn%60pi-manage%20createdb%60%5Cr%5Cn%5Cr%5Cnand%20result%20is%20ok%5Cr%5Cn%5Cr%5Cn%60%3CSQLAlchemy%20engine%3D%27sqlite%3A////home/ubuntu/pidea/privacyidea/data.sqlite%27%3E%60%5Cr%5Cn%5Cr%5Cnthen%3A%5Cr%5Cn%5Cr%5Cn%60./pi-manage%20db%20stamp%20%204f32a4e1bf3%60%5Cr%5Cn%5Cr%5Cnand%20result%20is%20ok.%20Then%5Cr%5Cn%5Cr%5Cn%60./pi-manage%20db%20upgrade%60%5Cr%5Cn%5Cr%5Cnand%20I%20got%20a%20lot%20of%20errors.%5Cr%5Cn%5Cr%5CnNow%2C%20when%20I%20try%20to%20create%20new%20migration%20runnning%20this%3A%5Cr%5Cn%5Cr%5Cn%60./pi-manage%20db%20migrate%60%5Cr%5Cn%5Cr%5Cnthe%20result%20is%3A%5Cr%5Cn%5Cr%5Cn%60alembic.util.CommandError%3A%20Target%20database%20is%20not%20up%20to%20date.%60%5Cr%5Cn%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222017-07-07T13%3A17%3A58Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/6554709%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/salvorapi%22%7D%7D%2C%20%7B%22body%22%3A%20%22Your%20last%20database%20version%20should%20be%203429d523e51f.%5Cr%5CnYou%20can%20see%20this%20via%5Cr%5Cn%5Cr%5Cn%20%20%20%20./pi-manage%20db%20history%5Cr%5Cn%5Cr%5Cnor%20you%20should%20see%20it%20in%20the%20alembic_version%20table.%5Cr%5Cn%5Cr%5CnThe%20command%5Cr%5Cn%5Cr%5Cn%20%20%20%20./pi-manage%20db%20migrate%5Cr%5Cn%5Cr%5Cnshould%20find%20the%20changes%20in%20the%20file%20%60%60privacyidea/models.py%60%60%20and%20autogenerate%20a%20migration%20script.%5Cr%5CnAre%20you%20running%20the%20commands%20in%20the%20virtualenv%3F%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222017-07-07T19%3A51%3A48Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/1908620%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%2C%20%7B%22body%22%3A%20%22Yes%2C%20it%20is.%5Cr%5Cn%60%60%60%5Cr%5Cnsqlite%3E%20SELECT%20%2A%20FROM%20alembic_version%3B%5Cr%5Cn3429d523e51f%5Cr%5Cn%5Cr%5Cn%60%60%60%5Cr%5CnCan%20be%20that%20I%27ve%20modified%20the%20%60audit_column_length%60%20and%20not%20the%20model%20directly%20%3F%22%2C%20%22created_at%22%3A%20%222017-07-08T09%3A00%3A14Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/6554709%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/salvorapi%22%7D%7D%2C%20%7B%22body%22%3A%20%22Yes%2C%20that%27s%20right.%20You%20must%20noch%20change%20the%20database%2C%20but%20the%20model%21%5Cr%5Cn%5Cr%5CnThen%20you%20generate%20the%20migration%20script%3A%5Cr%5Cn%5Cr%5Cn%20%20%20%20./pi-manage%20db%20migrate%5Cr%5Cn%5Cr%5Cnalembic%20checks%2C%20what%20is%20new%20in%20the%20model%20in%20contrast%20to%20the%20database%20and%20generates%20the%20migration%20script.%5Cr%5Cn%5Cr%5Cn%20%20%20%20./pi-manage%20db%20upgrade%5Cr%5Cn%5Cr%5Cnapplies%20all%20migration%20scripts.%5Cr%5Cn%5Cr%5CnSo%20if%20you%20changed%20the%20database%2C%20then%20alembic%20does%20not%20know%2C%20how%20you%20came%20there%2C%20so%20the%20database%20would%20be%20newer%2C%20or%20older%2C%20but%20at%20least%20%5C%22not%20up%20to%20date%5C%22.%5Cr%5Cn%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222017-07-08T11%3A07%3A32Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/1908620%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20also%20stumbled%20upon%20this%20issue%20%28because%20one%20of%20my%20token%27s%20serial%20numbers%20was%20longer%20than%2020%20characters%29.%20Thanks%20%40salvorapi%20for%20the%20contribution%21%20Do%20I%20see%20correctly%20that%20the%20only%20thing%20that%27s%20missing%20is%20the%20migration%20script%3F%20If%20that%27s%20the%20case%2C%20I%20can%20also%20try%20to%20generate%20that%20myself%2C%20if%20you%20want.%22%2C%20%22created_at%22%3A%20%222018-02-09T14%3A06%3A49Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/28243%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/fredreichbier%22%7D%7D%2C%20%7B%22body%22%3A%20%22Thank%20you%20%40fredreichbier.%20I%20tried%20to%20create%20the%20migration%20but%20without%20success.%20%3A%28%20%22%2C%20%22created_at%22%3A%20%222018-02-09T20%3A58%3A43Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/6554709%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/salvorapi%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20added%20a%20section%20about%20creating%20the%20migration%20script.%5Cr%5Cnhttps%3A//github.com/privacyidea/privacyidea/commit/568abb116dca36e46ac1f1bd9c32be6eeba8f580%5Cr%5Cn%5Cr%5CnActually%20I%20am%20not%20sure%2C%20if%20databases%20like%20Oracle%20can%20run%20into%20problem%2C%20since%20the%20overall%20lenght%20of%20all%20columns%20gets%20too%20long.%20I%20saw%20this%20some%20years%20ago...%22%2C%20%22created_at%22%3A%20%222018-02-09T21%3A59%3A22Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/1908620%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/privacyidea/privacyidea/pull/728#issuecomment-310321921'>General Comment</a></b>
- <a href='https://github.com/codecov-io'></a> # [Codecov](https://codecov.io/gh/privacyidea/privacyidea/pull/728?src=pr&el=h1) Report
> Merging [#728](https://codecov.io/gh/privacyidea/privacyidea/pull/728?src=pr&el=desc) into [master](https://codecov.io/gh/privacyidea/privacyidea/commit/512cbdb6c4b497c4d04006528d49bf0d98d752c6?src=pr&el=desc) will **decrease** coverage by `0.03%`.
> The diff coverage is `n/a`.
[Impacted file tree graph](https://codecov.io/gh/privacyidea/privacyidea/pull/728?src=pr&el=tree)
```diff
@@            Coverage Diff            @@
##           master    #728      +/-   ##
=========================================
- Coverage   95.34%   95.3%   -0.04%
=========================================
Files         121     121
Lines       14818   14818
=========================================
- Hits        14128   14123       -5
- Misses        690     695       +5
```
| [Impacted Files](https://codecov.io/gh/privacyidea/privacyidea/pull/728?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [privacyidea/models.py](https://codecov.io/gh/privacyidea/privacyidea/pull/728?src=pr&el=tree#diff-cHJpdmFjeWlkZWEvbW9kZWxzLnB5) | `98.68% <ø> (ø)` | :arrow_up: |
| [privacyidea/lib/tokens/u2f.py](https://codecov.io/gh/privacyidea/privacyidea/pull/728?src=pr&el=tree#diff-cHJpdmFjeWlkZWEvbGliL3Rva2Vucy91MmYucHk=) | `91.59% <0%> (-4.21%)` | :arrow_down: |
------
[Continue to review full report at Codecov](https://codecov.io/gh/privacyidea/privacyidea/pull/728?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/privacyidea/privacyidea/pull/728?src=pr&el=footer). Last update [512cbdb...03da416](https://codecov.io/gh/privacyidea/privacyidea/pull/728?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).
- <a href='https://github.com/cornelinux'></a> Thanks a lot for the heads up.
Each database change needs a migration script in *migrations/*.
The command
pi-manage db migrate
will create a default migration script (with some junk).
Could you also add this migration script and also add a try/except block, just like with the other migration scripts?
- <a href='https://github.com/salvorapi'></a> Hi,
I've cloned repository on my VM and create python env with requirements.txt
I try to do the command:
pi-manage createdb
and then
pi-manage db upgrade
but I have the error:
index ix_token_user_id already exists [SQL: u'CREATE INDEX ix_token_user_id ON token (user_id)']
How I do apply last upgrade on DB so next I will create new migration ?
Thank you.
Salvo.
- <a href='https://github.com/cornelinux'></a> Please run
./pi-manage
(You probably did this)
When you initially create the database you probably have not alembic versioning talbe in it. you need to create this like
./pi-manage db stamp  4f32a4e1bf33
(see http://privacyidea.readthedocs.io/en/latest/installation/upgrade.html?highlight=pi-manage%20stamp#manual-upgrade)
This ``stamp`` will create the version table andin this case set the version to the first version.
Now you can run
./pi-manage db upgrade
Well, you will get a lot of errors you can ignore, but now you have the talbe ``alembic_version``.
- <a href='https://github.com/salvorapi'></a> Hi,
what I've done is:
`pi-manage createdb`
and result is ok
`<SQLAlchemy engine='sqlite:////home/ubuntu/pidea/privacyidea/data.sqlite'>`
then:
`./pi-manage db stamp  4f32a4e1bf3`
and result is ok. Then
`./pi-manage db upgrade`
and I got a lot of errors.
Now, when I try to create new migration runnning this:
`./pi-manage db migrate`
the result is:
`alembic.util.CommandError: Target database is not up to date.`
- <a href='https://github.com/cornelinux'></a> Your last database version should be 3429d523e51f.
You can see this via
./pi-manage db history
or you should see it in the alembic_version table.
The command
./pi-manage db migrate
should find the changes in the file ``privacyidea/models.py`` and autogenerate a migration script.
Are you running the commands in the virtualenv?
- <a href='https://github.com/salvorapi'></a> Yes, it is.
```
sqlite> SELECT * FROM alembic_version;
3429d523e51f
```
Can be that I've modified the `audit_column_length` and not the model directly ?
- <a href='https://github.com/cornelinux'></a> Yes, that's right. You must noch change the database, but the model!
Then you generate the migration script:
./pi-manage db migrate
alembic checks, what is new in the model in contrast to the database and generates the migration script.
./pi-manage db upgrade
applies all migration scripts.
So if you changed the database, then alembic does not know, how you came there, so the database would be newer, or older, but at least "not up to date".
- <a href='https://github.com/fredreichbier'></a> I also stumbled upon this issue (because one of my token's serial numbers was longer than 20 characters). Thanks @salvorapi for the contribution! Do I see correctly that the only thing that's missing is the migration script? If that's the case, I can also try to generate that myself, if you want.
- <a href='https://github.com/salvorapi'></a> Thank you @fredreichbier. I tried to create the migration but without success. :(
- <a href='https://github.com/cornelinux'></a> I added a section about creating the migration script.
https://github.com/privacyidea/privacyidea/commit/568abb116dca36e46ac1f1bd9c32be6eeba8f580
Actually I am not sure, if databases like Oracle can run into problem, since the overall lenght of all columns gets too long. I saw this some years ago...

<a href='https://www.codereviewhub.com/privacyidea/privacyidea/pull/728?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/privacyidea/privacyidea/pull/728?approve=1'></a>&nbsp;<a href='https://github.com/privacyidea/privacyidea/pull/728'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by cornelinux** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/privacyidea/privacyidea/pull/728'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by cornelinux** [comment]
Thanks a lot for the heads up.
Each database change needs a migration script in *migrations/*.
The command 

   pi-manage db migrate

will create a default migration script (with some junk). 
Could you also add this migration script and also add a try/except block, just like with the other migration scripts?

**Comment by salvorapi** [comment]
Hi,

I've cloned repository on my VM and create python env with requirements.txt
I try to do the command:

pi-manage createdb

and then

pi-manage db upgrade

but I have the error:

index ix_token_user_id already exists [SQL: u'CREATE INDEX ix_token_user_id ON token (user_id)']

How I do apply last upgrade on DB so next I will create new migration ?

Thank you.

Salvo.

**Comment by cornelinux** [comment]
Please run

    ./pi-manage

(You probably did this)

When you initially create the database you probably have not alembic versioning talbe in it. you need to create this like

    ./pi-manage db stamp  4f32a4e1bf33 

(see http://privacyidea.readthedocs.io/en/latest/installation/upgrade.html?highlight=pi-manage%20stamp#manual-upgrade)
This ``stamp`` will create the version table andin this case set the version to the first version.
Now you can run

    ./pi-manage db upgrade

Well, you will get a lot of errors you can ignore, but now you have the talbe ``alembic_version``.

**Comment by salvorapi** [comment]
Hi,

what I've done is:

`pi-manage createdb`

and result is ok

`<SQLAlchemy engine='sqlite:////home/ubuntu/pidea/privacyidea/data.sqlite'>`

then:

`./pi-manage db stamp  4f32a4e1bf3`

and result is ok. Then

`./pi-manage db upgrade`

and I got a lot of errors.

Now, when I try to create new migration runnning this:

`./pi-manage db migrate`

the result is:

`alembic.util.CommandError: Target database is not up to date.`

**Comment by cornelinux** [comment]
Your last database version should be 3429d523e51f.
You can see this via

    ./pi-manage db history

or you should see it in the alembic_version table.

The command

    ./pi-manage db migrate

should find the changes in the file ``privacyidea/models.py`` and autogenerate a migration script.
Are you running the commands in the virtualenv?

**Comment by salvorapi** [comment]
Yes, it is.
```
sqlite> SELECT * FROM alembic_version;
3429d523e51f

```
Can be that I've modified the `audit_column_length` and not the model directly ?

**Comment by cornelinux** [comment]
Yes, that's right. You must noch change the database, but the model!

Then you generate the migration script:

    ./pi-manage db migrate

alembic checks, what is new in the model in contrast to the database and generates the migration script.

    ./pi-manage db upgrade

applies all migration scripts.

So if you changed the database, then alembic does not know, how you came there, so the database would be newer, or older, but at least "not up to date".

**Comment by fredreichbier** [comment]
I also stumbled upon this issue (because one of my token's serial numbers was longer than 20 characters). Thanks @salvorapi for the contribution! Do I see correctly that the only thing that's missing is the migration script? If that's the case, I can also try to generate that myself, if you want.

**Comment by salvorapi** [comment]
Thank you @fredreichbier. I tried to create the migration but without success. :(

**Comment by cornelinux** [comment]
I added a section about creating the migration script.
https://github.com/privacyidea/privacyidea/commit/568abb116dca36e46ac1f1bd9c32be6eeba8f580

Actually I am not sure, if databases like Oracle can run into problem, since the overall lenght of all columns gets too long. I saw this some years ago...

**Comment by fredreichbier** [comment]
Hi @salvorapi, I imported your commits in my fork and tried to add a migration script. I'll close this PR -- let's continue the discussion in #929.

**Pull request closed without merging**
