### PR TITLE
Support webAuthn token without sign_count

### LINKED ISSUE #2361: Support webauthn token without sign_count
Some webauthn tokens (f.e. Apple devices) do not implement a sign_count. We do not currently support this.

### PR DESCRIPTION
**Pull request by NuvandaPV**
fixes #2361

### CODE REVIEW

**Comment by NuvandaPV** [comment]
pep8ify

**Comment by NuvandaPV** [comment]
@pep8speaks pep8ify

**Comment by NuvandaPV** [comment]
@plettich In theory there should be another test case here, that asserts that the AuthenticationRejectedException is not raised if sign_count is unsupported (i.e. both the stored sign_count and the sign_count in the response are zero), but I don't want to add even more binary blobs to test_lib_tokens_webauthn.py. The real solution would be implementing #2094, but that is of course a bigger undertaking.

**Review by plettich — APPROVED** [review]
Looks good.

**Pull request merged**
