### PR TITLE
1233/hide buttons

### PR DESCRIPTION
**Pull request by cornelinux**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/privacyidea/privacyidea/pull/1282%23issuecomment-432672611%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/1282%23issuecomment-434590543%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/1282%23issuecomment-434592617%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/1282%23issuecomment-437835196%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/1282%23issuecomment-437840669%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/privacyidea/privacyidea/pull/1282%23issuecomment-432672611%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22How%20does%20hiding%20the%20resync%20row%20change%20the%20standard%20behaviour%3F%5Cr%5CnResync%20does%20not%20contain%20any%20information%2C%20so%20%5C%22standard%5C%22%20would%20be%20to%20hide%20the%20complete%20row.%5Cr%5Cn%5Cr%5CnIn%20contrast%20to%20%5C%22reset%5C%22%20the%20fail%20counter%3A%20There%20is%20information%20about%20the%20count%20of%20the%20failcounter%2C%20this%20is%20why%20we%20would%20only%20hide%20the%20button%2C%20not%20the%20complete%20row.%20I.e.%20if%20information%20exists%2C%20it%20is%20visislbe.%5Cr%5Cn%5Cr%5Cn%5C%22Edit%5C%22%20buttons%3A%20yes.%20%3A-%29%22%2C%20%22created_at%22%3A%20%222018-10-24T14%3A08%3A23Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/1908620%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%2C%20%7B%22body%22%3A%20%22regarding%201%3A%20Sorry%20for%20the%20confusing%20wording%21%20Assume%20a%20user%20does%20not%20have%20resync%20rights.%20Before%20this%20change%2C%20the%20resync%20row%20was%20visible.%20After%20this%20change%2C%20the%20resync%20row%20is%20invisible.%20This%20is%20a%20change%20of%20behavior%2C%20but%20I%20think%20it%20makes%20sense.%20%3A-%29%5Cr%5Cn%5Cr%5Cnregarding%202%3A%20Do%20you%20want%20to%20implement%20the%20hiding%20%5C%22edit%5C%22%20buttons%20in%20this%20PR%2C%20or%20should%20we%20do%20another%20one%3F%22%2C%20%22created_at%22%3A%20%222018-10-31T07%3A42%3A22Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/28243%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/fredreichbier%22%7D%7D%2C%20%7B%22body%22%3A%20%22regarding%201%3A%20It%20is%20a%20change%20of%20behaviour.%20It%20does%20not%20matter.%20We%20are%20merging%20this%20into%20master.%20There%20is%20no%20sense%20in%20having%20the%20resync%20row%20visible%2C%20if%20the%20user%20is%20not%20allowed%20to%20resync.%5Cr%5Cn%5Cr%5Cnregarding%202%3A%20You%20are%20right.%20We%20probalby%20also%20should%20hide%20this%20one%20-%20also%20in%20the%20PR%22%2C%20%22created_at%22%3A%20%222018-10-31T07%3A52%3A06Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/1908620%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40fredreichbier%20regarding%202%3A%20I%20think%20I%20am%20done%2C%20now.%5Cr%5CnYou%20are%20welcome%20to%20merge%2C%20if%20you%20like%20what%20I%20did%20here.%20%28I%20like%20it%3B-%29%22%2C%20%22created_at%22%3A%20%222018-11-12T10%3A45%3A47Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/1908620%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%2C%20%7B%22body%22%3A%20%22%23%20%5BCodecov%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1282%3Fsrc%3Dpr%26el%3Dh1%29%20Report%5Cn%3E%20Merging%20%5B%231282%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1282%3Fsrc%3Dpr%26el%3Ddesc%29%20into%20%5Bmaster%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/commit/7a18294290e25aca98acf59c6e5064fa61c9d85f%3Fsrc%3Dpr%26el%3Ddesc%29%20will%20%2A%2Aincrease%2A%2A%20coverage%20by%20%600.05%25%60.%5Cn%3E%20The%20diff%20coverage%20is%20%60100%25%60.%5Cn%5Cn%5B%21%5BImpacted%20file%20tree%20graph%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1282/graphs/tree.svg%3Fwidth%3D650%26token%3D7nHLZki60B%26height%3D150%26src%3Dpr%29%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1282%3Fsrc%3Dpr%26el%3Dtree%29%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20Coverage%20Diff%20%20%20%20%20%20%20%20%20%20%20%20%20%40%40%5Cn%23%23%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%231282%20%20%20%20%20%20%2B/-%20%20%20%23%23%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%2B%20Coverage%20%20%20%2095.8%25%20%20%2095.86%25%20%20%20%2B0.05%25%20%20%20%20%20%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%20%20Files%20%20%20%20%20%20%20%20%20141%20%20%20%20%20%20142%20%20%20%20%20%20%20%2B1%20%20%20%20%20%5Cn%20%20Lines%20%20%20%20%20%20%2017150%20%20%20%2018182%20%20%20%20%2B1032%20%20%20%20%20%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%2B%20Hits%20%20%20%20%20%20%20%2016431%20%20%20%2017430%20%20%20%20%20%2B999%20%20%20%20%20%5Cn-%20Misses%20%20%20%20%20%20%20%20719%20%20%20%20%20%20752%20%20%20%20%20%20%2B33%5Cn%60%60%60%5Cn%5Cn%5Cn%7C%20%5BImpacted%20Files%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1282%3Fsrc%3Dpr%26el%3Dtree%29%20%7C%20Coverage%20%5Cu0394%20%7C%20%7C%5Cn%7C---%7C---%7C---%7C%5Cn%7C%20%5Bprivacyidea/api/lib/postpolicy.py%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1282/diff%3Fsrc%3Dpr%26el%3Dtree%23diff-cHJpdmFjeWlkZWEvYXBpL2xpYi9wb3N0cG9saWN5LnB5%29%20%7C%20%6096.67%25%20%3C100%25%3E%20%28%2B0.03%25%29%60%20%7C%20%3Aarrow_up%3A%20%7C%5Cn%7C%20%5Bprivacyidea/lib/policy.py%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1282/diff%3Fsrc%3Dpr%26el%3Dtree%23diff-cHJpdmFjeWlkZWEvbGliL3BvbGljeS5weQ%3D%3D%29%20%7C%20%6099.4%25%20%3C100%25%3E%20%28%5Cu00f8%29%60%20%7C%20%3Aarrow_up%3A%20%7C%5Cn%7C%20%5Bprivacyidea/lib/security/aeshsm.py%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1282/diff%3Fsrc%3Dpr%26el%3Dtree%23diff-cHJpdmFjeWlkZWEvbGliL3NlY3VyaXR5L2Flc2hzbS5weQ%3D%3D%29%20%7C%20%6029.62%25%20%3C0%25%3E%20%28-6.96%25%29%60%20%7C%20%3Aarrow_down%3A%20%7C%5Cn%7C%20%5Bprivacyidea/lib/sqlutils.py%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1282/diff%3Fsrc%3Dpr%26el%3Dtree%23diff-cHJpdmFjeWlkZWEvbGliL3NxbHV0aWxzLnB5%29%20%7C%20%60100%25%20%3C0%25%3E%20%28%5Cu00f8%29%60%20%7C%20%7C%5Cn%7C%20%5Bprivacyidea/lib/resolvers/LDAPIdResolver.py%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1282/diff%3Fsrc%3Dpr%26el%3Dtree%23diff-cHJpdmFjeWlkZWEvbGliL3Jlc29sdmVycy9MREFQSWRSZXNvbHZlci5weQ%3D%3D%29%20%7C%20%6093.98%25%20%3C0%25%3E%20%28%2B0.01%25%29%60%20%7C%20%3Aarrow_up%3A%20%7C%5Cn%7C%20%5Bprivacyidea/lib/user.py%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1282/diff%3Fsrc%3Dpr%26el%3Dtree%23diff-cHJpdmFjeWlkZWEvbGliL3VzZXIucHk%3D%29%20%7C%20%6099.74%25%20%3C0%25%3E%20%28%2B0.08%25%29%60%20%7C%20%3Aarrow_up%3A%20%7C%5Cn%7C%20%5Bprivacyidea/lib/token.py%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1282/diff%3Fsrc%3Dpr%26el%3Dtree%23diff-cHJpdmFjeWlkZWEvbGliL3Rva2VuLnB5%29%20%7C%20%6096.51%25%20%3C0%25%3E%20%28%2B1.32%25%29%60%20%7C%20%3Aarrow_up%3A%20%7C%5Cn%7C%20%5Bprivacyidea/lib/auditmodules/sqlaudit.py%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1282/diff%3Fsrc%3Dpr%26el%3Dtree%23diff-cHJpdmFjeWlkZWEvbGliL2F1ZGl0bW9kdWxlcy9zcWxhdWRpdC5weQ%3D%3D%29%20%7C%20%6095.51%25%20%3C0%25%3E%20%28%2B1.48%25%29%60%20%7C%20%3Aarrow_up%3A%20%7C%5Cn%7C%20%5Bprivacyidea/lib/tokens/u2f.py%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1282/diff%3Fsrc%3Dpr%26el%3Dtree%23diff-cHJpdmFjeWlkZWEvbGliL3Rva2Vucy91MmYucHk%3D%29%20%7C%20%6095.83%25%20%3C0%25%3E%20%28%2B2.5%25%29%60%20%7C%20%3Aarrow_up%3A%20%7C%5Cn%5Cn------%5Cn%5Cn%5BContinue%20to%20review%20full%20report%20at%20Codecov%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1282%3Fsrc%3Dpr%26el%3Dcontinue%29.%5Cn%3E%20%2A%2ALegend%2A%2A%20-%20%5BClick%20here%20to%20learn%20more%5D%28https%3A//docs.codecov.io/docs/codecov-delta%29%5Cn%3E%20%60%5Cu0394%20%3D%20absolute%20%3Crelative%3E%20%28impact%29%60%2C%20%60%5Cu00f8%20%3D%20not%20affected%60%2C%20%60%3F%20%3D%20missing%20data%60%5Cn%3E%20Powered%20by%20%5BCodecov%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1282%3Fsrc%3Dpr%26el%3Dfooter%29.%20Last%20update%20%5B7a18294...2a235cc%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1282%3Fsrc%3Dpr%26el%3Dlastupdated%29.%20Read%20the%20%5Bcomment%20docs%5D%28https%3A//docs.codecov.io/docs/pull-request-comments%29.%5Cn%22%2C%20%22created_at%22%3A%20%222018-11-12T11%3A05%3A06Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/in/254%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/apps/codecov%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/privacyidea/privacyidea/pull/1282#issuecomment-432672611'>General Comment</a></b>
- <a href='https://github.com/cornelinux'></a> How does hiding the resync row change the standard behaviour?
Resync does not contain any information, so "standard" would be to hide the complete row.
In contrast to "reset" the fail counter: There is information about the count of the failcounter, this is why we would only hide the button, not the complete row. I.e. if information exists, it is visislbe.
"Edit" buttons: yes. :-)
- <a href='https://github.com/fredreichbier'></a> regarding 1: Sorry for the confusing wording! Assume a user does not have resync rights. Before this change, the resync row was visible. After this change, the resync row is invisible. This is a change of behavior, but I think it makes sense. :-)
regarding 2: Do you want to implement the hiding "edit" buttons in this PR, or should we do another one?
- <a href='https://github.com/cornelinux'></a> regarding 1: It is a change of behaviour. It does not matter. We are merging this into master. There is no sense in having the resync row visible, if the user is not allowed to resync.
regarding 2: You are right. We probalby also should hide this one - also in the PR
- <a href='https://github.com/cornelinux'></a> @fredreichbier regarding 2: I think I am done, now.
You are welcome to merge, if you like what I did here. (I like it;-)
- <a href='https://github.com/apps/codecov'></a> # [Codecov](https://codecov.io/gh/privacyidea/privacyidea/pull/1282?src=pr&el=h1) Report
> Merging [#1282](https://codecov.io/gh/privacyidea/privacyidea/pull/1282?src=pr&el=desc) into [master](https://codecov.io/gh/privacyidea/privacyidea/commit/7a18294290e25aca98acf59c6e5064fa61c9d85f?src=pr&el=desc) will **increase** coverage by `0.05%`.
> The diff coverage is `100%`.
[Impacted file tree graph](https://codecov.io/gh/privacyidea/privacyidea/pull/1282?src=pr&el=tree)
```diff
@@            Coverage Diff             @@
##           master    #1282      +/-   ##
==========================================
+ Coverage    95.8%   95.86%   +0.05%
==========================================
Files         141      142       +1
Lines       17150    18182    +1032
==========================================
+ Hits        16431    17430     +999
- Misses        719      752      +33
```
| [Impacted Files](https://codecov.io/gh/privacyidea/privacyidea/pull/1282?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [privacyidea/api/lib/postpolicy.py](https://codecov.io/gh/privacyidea/privacyidea/pull/1282/diff?src=pr&el=tree#diff-cHJpdmFjeWlkZWEvYXBpL2xpYi9wb3N0cG9saWN5LnB5) | `96.67% <100%> (+0.03%)` | :arrow_up: |
| [privacyidea/lib/policy.py](https://codecov.io/gh/privacyidea/privacyidea/pull/1282/diff?src=pr&el=tree#diff-cHJpdmFjeWlkZWEvbGliL3BvbGljeS5weQ==) | `99.4% <100%> (ø)` | :arrow_up: |
| [privacyidea/lib/security/aeshsm.py](https://codecov.io/gh/privacyidea/privacyidea/pull/1282/diff?src=pr&el=tree#diff-cHJpdmFjeWlkZWEvbGliL3NlY3VyaXR5L2Flc2hzbS5weQ==) | `29.62% <0%> (-6.96%)` | :arrow_down: |
| [privacyidea/lib/sqlutils.py](https://codecov.io/gh/privacyidea/privacyidea/pull/1282/diff?src=pr&el=tree#diff-cHJpdmFjeWlkZWEvbGliL3NxbHV0aWxzLnB5) | `100% <0%> (ø)` | |
| [privacyidea/lib/resolvers/LDAPIdResolver.py](https://codecov.io/gh/privacyidea/privacyidea/pull/1282/diff?src=pr&el=tree#diff-cHJpdmFjeWlkZWEvbGliL3Jlc29sdmVycy9MREFQSWRSZXNvbHZlci5weQ==) | `93.98% <0%> (+0.01%)` | :arrow_up: |
| [privacyidea/lib/user.py](https://codecov.io/gh/privacyidea/privacyidea/pull/1282/diff?src=pr&el=tree#diff-cHJpdmFjeWlkZWEvbGliL3VzZXIucHk=) | `99.74% <0%> (+0.08%)` | :arrow_up: |
| [privacyidea/lib/token.py](https://codecov.io/gh/privacyidea/privacyidea/pull/1282/diff?src=pr&el=tree#diff-cHJpdmFjeWlkZWEvbGliL3Rva2VuLnB5) | `96.51% <0%> (+1.32%)` | :arrow_up: |
| [privacyidea/lib/auditmodules/sqlaudit.py](https://codecov.io/gh/privacyidea/privacyidea/pull/1282/diff?src=pr&el=tree#diff-cHJpdmFjeWlkZWEvbGliL2F1ZGl0bW9kdWxlcy9zcWxhdWRpdC5weQ==) | `95.51% <0%> (+1.48%)` | :arrow_up: |
| [privacyidea/lib/tokens/u2f.py](https://codecov.io/gh/privacyidea/privacyidea/pull/1282/diff?src=pr&el=tree#diff-cHJpdmFjeWlkZWEvbGliL3Rva2Vucy91MmYucHk=) | `95.83% <0%> (+2.5%)` | :arrow_up: |
------
[Continue to review full report at Codecov](https://codecov.io/gh/privacyidea/privacyidea/pull/1282?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/privacyidea/privacyidea/pull/1282?src=pr&el=footer). Last update [7a18294...2a235cc](https://codecov.io/gh/privacyidea/privacyidea/pull/1282?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

<a href='https://www.codereviewhub.com/privacyidea/privacyidea/pull/1282?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/privacyidea/privacyidea/pull/1282?approve=1'></a>&nbsp;<a href='https://github.com/privacyidea/privacyidea/pull/1282'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by cornelinux** [comment]
How does hiding the resync row change the standard behaviour?
Resync does not contain any information, so "standard" would be to hide the complete row.

In contrast to "reset" the fail counter: There is information about the count of the failcounter, this is why we would only hide the button, not the complete row. I.e. if information exists, it is visislbe.

"Edit" buttons: yes. :-)

**Comment by fredreichbier** [comment]
regarding 1: Sorry for the confusing wording! Assume a user does not have resync rights. Before this change, the resync row was visible. After this change, the resync row is invisible. This is a change of behavior, but I think it makes sense. :-)

regarding 2: Do you want to implement the hiding "edit" buttons in this PR, or should we do another one?

**Comment by cornelinux** [comment]
regarding 1: It is a change of behaviour. It does not matter. We are merging this into master. There is no sense in having the resync row visible, if the user is not allowed to resync.

regarding 2: You are right. We probalby also should hide this one - also in the PR

**Comment by cornelinux** [comment]
@fredreichbier regarding 2: I think I am done, now.
You are welcome to merge, if you like what I did here. (I like it;-)

**Pull request merged**
