### PR TITLE
Update to CircleCI 2.0 from 1.0

### LINKED ISSUE #1208: Update CircleCI configuration
CircleCI 1.0 will be unsupported soon. Update configuration to support CircleCI 2.0.

### PR DESCRIPTION
**Pull request by plettich**
Created a new configuration for CircleCI 2.0 since 1.0 will be disabled
soon.
Tried to mimic the original behaviour as close as possible using the new
configuration.
Currently we only build privacyIDEA using `setup.py` and `make
builddeb-nosign` in order to catch failures in these steps. There is
(currently) no test for functionality!
Also the unit tests won't be run.

Fixes #1208
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/privacyidea/privacyidea/pull/1209%23issuecomment-417695614%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/1209%23issuecomment-418162753%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/1209%23issuecomment-418307991%22%2C%20%22https%3A//github.com/privacyidea/privacyidea/pull/1209%23issuecomment-418311081%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/privacyidea/privacyidea/pull/1209%23issuecomment-417695614%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%20%5BCodecov%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1209%3Fsrc%3Dpr%26el%3Dh1%29%20Report%5Cn%3E%20Merging%20%5B%231209%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1209%3Fsrc%3Dpr%26el%3Ddesc%29%20into%20%5Bmaster%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/commit/43ce2d0a20f836046bed0d6cd62a81759df0f4a1%3Fsrc%3Dpr%26el%3Ddesc%29%20will%20%2A%2Anot%20change%2A%2A%20coverage.%5Cn%3E%20The%20diff%20coverage%20is%20%60n/a%60.%5Cn%5Cn%5B%21%5BImpacted%20file%20tree%20graph%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1209/graphs/tree.svg%3Fwidth%3D650%26token%3D7nHLZki60B%26height%3D150%26src%3Dpr%29%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1209%3Fsrc%3Dpr%26el%3Dtree%29%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20Coverage%20Diff%20%20%20%20%20%20%20%20%20%20%20%40%40%5Cn%23%23%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%231209%20%20%20%2B/-%20%20%20%23%23%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%20%20Coverage%20%20%2095.77%25%20%20%2095.77%25%20%20%20%20%20%20%20%20%20%20%20%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%20%20Files%20%20%20%20%20%20%20%20%20141%20%20%20%20%20%20141%20%20%20%20%20%20%20%20%20%20%20%5Cn%20%20Lines%20%20%20%20%20%20%2017120%20%20%20%2017120%20%20%20%20%20%20%20%20%20%20%20%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%20%20Hits%20%20%20%20%20%20%20%2016396%20%20%20%2016396%20%20%20%20%20%20%20%20%20%20%20%5Cn%20%20Misses%20%20%20%20%20%20%20%20724%20%20%20%20%20%20724%5Cn%60%60%60%5Cn%5Cn%5Cn%5Cn------%5Cn%5Cn%5BContinue%20to%20review%20full%20report%20at%20Codecov%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1209%3Fsrc%3Dpr%26el%3Dcontinue%29.%5Cn%3E%20%2A%2ALegend%2A%2A%20-%20%5BClick%20here%20to%20learn%20more%5D%28https%3A//docs.codecov.io/docs/codecov-delta%29%5Cn%3E%20%60%5Cu0394%20%3D%20absolute%20%3Crelative%3E%20%28impact%29%60%2C%20%60%5Cu00f8%20%3D%20not%20affected%60%2C%20%60%3F%20%3D%20missing%20data%60%5Cn%3E%20Powered%20by%20%5BCodecov%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1209%3Fsrc%3Dpr%26el%3Dfooter%29.%20Last%20update%20%5B43ce2d0...a7415d0%5D%28https%3A//codecov.io/gh/privacyidea/privacyidea/pull/1209%3Fsrc%3Dpr%26el%3Dlastupdated%29.%20Read%20the%20%5Bcomment%20docs%5D%28https%3A//docs.codecov.io/docs/pull-request-comments%29.%5Cn%22%2C%20%22created_at%22%3A%20%222018-08-31T15%3A12%3A51Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/in/254%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/apps/codecov%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40plettich%20%20This%20is%20ok%20for%20me.%5Cr%5CnYou%20did%20not%20specify%20a%20reviewer%20-%20should%20we%20merge%3F%22%2C%20%22created_at%22%3A%20%222018-09-03T17%3A04%3A54Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/1908620%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%2C%20%7B%22body%22%3A%20%22currently%20there%20is%20no%20harm%20in%20having%20this%2C%20i%20think.%20Whether%20we%20should%20focus%20on%20Travis%20or%20Circle%20or%20keep%20all%20the%20options%20open%20should%20be%20discussed.%5Cr%5CnI%20was%20looking%20at%20CircleCI%20for%20testing%20%231127%20but%20i%20think%20Travis%20would%20the%20better%20choice.%22%2C%20%22created_at%22%3A%20%222018-09-04T09%3A49%3A02Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars0.githubusercontent.com/u/37443810%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/plettich%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20think%20travis%20is%20indeed%20the%20better%20choice%20for%20our%20unit%20tests.%20%5Cr%5CnWe%20can%20see%2C%20if%20we%20can%20incorporate%20circle%20ci%20for%20integration%20tests%20in%20future%20more.%22%2C%20%22created_at%22%3A%20%222018-09-04T10%3A00%3A32Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/1908620%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/privacyidea/privacyidea/pull/1209#issuecomment-417695614'>General Comment</a></b>
- <a href='https://github.com/apps/codecov'></a> # [Codecov](https://codecov.io/gh/privacyidea/privacyidea/pull/1209?src=pr&el=h1) Report
> Merging [#1209](https://codecov.io/gh/privacyidea/privacyidea/pull/1209?src=pr&el=desc) into [master](https://codecov.io/gh/privacyidea/privacyidea/commit/43ce2d0a20f836046bed0d6cd62a81759df0f4a1?src=pr&el=desc) will **not change** coverage.
> The diff coverage is `n/a`.
[Impacted file tree graph](https://codecov.io/gh/privacyidea/privacyidea/pull/1209?src=pr&el=tree)
```diff
@@           Coverage Diff           @@
##           master    #1209   +/-   ##
=======================================
Coverage   95.77%   95.77%
=======================================
Files         141      141
Lines       17120    17120
=======================================
Hits        16396    16396
Misses        724      724
```
------
[Continue to review full report at Codecov](https://codecov.io/gh/privacyidea/privacyidea/pull/1209?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/privacyidea/privacyidea/pull/1209?src=pr&el=footer). Last update [43ce2d0...a7415d0](https://codecov.io/gh/privacyidea/privacyidea/pull/1209?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).
- <a href='https://github.com/cornelinux'></a> @plettich  This is ok for me.
You did not specify a reviewer - should we merge?
- <a href='https://github.com/plettich'></a> currently there is no harm in having this, i think. Whether we should focus on Travis or Circle or keep all the options open should be discussed.
I was looking at CircleCI for testing #1127 but i think Travis would the better choice.
- <a href='https://github.com/cornelinux'></a> I think travis is indeed the better choice for our unit tests.
We can see, if we can incorporate circle ci for integration tests in future more.

<a href='https://www.codereviewhub.com/privacyidea/privacyidea/pull/1209?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/privacyidea/privacyidea/pull/1209?approve=1'></a>&nbsp;<a href='https://github.com/privacyidea/privacyidea/pull/1209'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by cornelinux** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/privacyidea/privacyidea/pull/1209'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by cornelinux** [comment]
@plettich  This is ok for me.
You did not specify a reviewer - should we merge?

**Comment by plettich** [comment]
currently there is no harm in having this, i think. Whether we should focus on Travis or Circle or keep all the options open should be discussed.
I was looking at CircleCI for testing #1127 but i think Travis would the better choice.

**Comment by cornelinux** [comment]
I think travis is indeed the better choice for our unit tests. 
We can see, if we can incorporate circle ci for integration tests in future more.

**Pull request merged**
