### PR TITLE
Add setup instructions for nose to the README

### PR DESCRIPTION
**Pull request by NuvandaPV**

### CODE REVIEW

**Comment by NuvandaPV** [comment]
fixes #1779

**Comment by fredreichbier** [comment]
The changes look fine to me! But as discussed in #1787, maybe we should use this opportunity to switch to pytest.

**Comment by NuvandaPV** [comment]
Shall I amend this PR or open a new one?

**Comment by fredreichbier** [comment]
You could either amend this PR and we just squash the commits, or you open a new one, or you force-push to this one. As you prefer :)

**Comment by fredreichbier** [comment]
OK, let's merge this first and do the migration to pytest later.

**Pull request merged**
