### PR TITLE
feat: add Czech translation

### PR DESCRIPTION
**Pull request by melanger**

### CODE REVIEW

**Comment by cornelinux** [comment]
Hello @melanger ,
thank you for your work and effort for the czech translation.
We are now using weblate for translations, could you please add your translation via weblate.
See https://privacyidea.readthedocs.io/en/latest/faq/translation.html
Thanks!

**Comment by cornelinux** [comment]
OK, it seems like you did so.

**Comment by melanger** [comment]
> Hello @melanger , thank you for your work and effort for the czech translation. We are now using weblate for translations, could you please add your translation via weblate. See https://privacyidea.readthedocs.io/en/latest/faq/translation.html Thanks!

Hi @cornelinux, I added my translations via Weblate, but that does not make them available in privacyIDEA. I had to also regenerate translations.js and add the new language to the places mentioned in documentation.

**Comment by melanger** [comment]
@cornelinux I created https://github.com/privacyidea/privacyidea/pull/2962 instead, which includes only changes done to the code.

For the up-to-date translations to be available, `translations.js` needs to be regenerated.

**Comment by cornelinux** [comment]
Hello  @melanger 
You do not need to generate the translations.js, this happens during our building process.
But please open a PR with the added "cs" to the `Makefile` and `app.py`.

**Comment by melanger** [comment]
> please open a PR with the added "cs" to the `Makefile` and `app.py`.

See https://github.com/privacyidea/privacyidea/pull/2962

**Pull request closed without merging**
