### PR TITLE
JWT Token Resolver: Impelment a Token Resolver

### PR DESCRIPTION
**Pull request by cparkins**
This code should most of the concerns posed by Issue #3618 by implementing the higher level functionality of allowing JWT Tokens to be validated.  Currently the ability to validate the Issuer was not part of my testing requirements, but could easily be added. I also believe that further support could be added to implement OIDC standards including the ability to list users in an Organization.

### CODE REVIEW

**Comment by cparkins** [comment]
@plettich - Once I resolve the lint issues, I'd like to see if you could review this change?

**Comment by nilsbehlen** [comment]
Hi, thanks for your contribution. We will of course review it, but it might take some more time as we currently have some hickups with the release 3.10.

**Comment by nilsbehlen** [comment]
Hi again. I would like to understand your code better.
Can you elaborate why you chose to implement a resolver? In the issue you referenced, there is no notion of an implementation via a resolver. 
Have you thought of alternative implementations? 
What is the implication of using this resolver in combination with other resolvers when resolving users?

**Comment by nilsbehlen** [comment]
Thanks for explaining. Another naive idea (which might be stupid down the line) would be a token type. We will need to discuss this some more, so we not only cover your use case with the implementation but offer a broad solution.
You probably provided the code already to make things work, we might just have to move it around a bit :)

**Comment by cparkins** [comment]
@nilsbehlen This is intended only as a first attempt. I think full OAuth/OpenID Connect support would be nice to have in the future.  But that was a bit beyond our simple use case of validating JWT solely.

**Comment by cornelinux** [comment]
@cparkins To me this sounds as if this is only about login to the selfservice portal.

How would authentication look like? You need to assign 2nd factors/token to user objects, that are currently found in a/via a resolver.
Maybe you should explain a bit more your overall scenario and we should open an issue and discuss this there?

**Comment by cparkins** [comment]
@cornelinux - Essentially the idea was to only allow access to the self-service portal. In my use case I have been challenged with only being able to validate a user by a JWT Token with a public token. I am able to do that with this code but storing that users User Id seems to be problematic because the Users cannot be listed.  I believe there are other Resolvers with these same limitations but I have no experience with them.

**Comment by cparkins** [comment]
@nilsbehlen I wanted to discuss your comment a bit more, is this the best way to do that or should I open an issue?

> Thanks for explaining. Another naive idea (which might be stupid down the line) would be a token type. We will need to discuss this some more, so we not only cover your use case with the implementation but offer a broad solution. You probably provided the code already to make things work, we might just have to move it around a bit :)

I like the idea of a 'Token Type' but don't know exactly what you mean by that. Can you elaborate?

@cornelinux I was wondering if you had anything to add to my idea?

**Pull request closed without merging**
