### PR TITLE
Baseline styles

### PR DESCRIPTION
**Pull request by NuvandaPV**
Add some protected space around floating input elements to keep them from clashing with the baseline.

### CODE REVIEW

**Comment by NuvandaPV** [comment]
relates #955

**Comment by NuvandaPV** [comment]
fixes #1484

**Comment by plettich** [comment]
I thought about something like this: https://jsfiddle.net/kqhj2s3p/

**Comment by NuvandaPV** [comment]
I don't really wanna go there, since making this work in practice will require `calc()` which will do some freaky stuff in IE.

**Comment by NuvandaPV** [comment]
@plettich how is this? Works in all browsers I have tested and at least shouldn't make things any worse in browsers where it is not supported (IE doesn't allow `*::after { display: block; }`, but that just means the whole fix does nothing).

**Pull request merged**
